// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EswatiniEmployees.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260905084819_AddCompanyAndEmployeeSeedData")]
    partial class AddCompanyAndEmployeeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "Plot 45, Matsapha Industrial Estate",
                            Country = "Eswatini",
                            Name = "Eswatini Textile Ltd"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Address = "102 King Mswati III Ave, Nhlangano",
                            Country = "Eswatini",
                            Name = "Royal Garments Eswatini"
                        },
                        new
                        {
                            Id = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Address = "Suite 201, Corporate Place, Mbabane",
                            Country = "Eswatini",
                            Name = "Mbabane Tech Solutions"
                        },
                        new
                        {
                            Id = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Address = "Mill Road, Simunye",
                            Country = "Eswatini",
                            Name = "Swazi Sugar Processors"
                        },
                        new
                        {
                            Id = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Address = "Main Road, Pigg's Peak",
                            Country = "Eswatini",
                            Name = "Peak Timber Products"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Age = 28,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Sibusiso Dlamini",
                            Position = "QA Supervisor"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Age = 32,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Nokuthula Zwane",
                            Position = "Pattern Maker"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000001"),
                            Age = 41,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Bheki Nkambule",
                            Position = "Plant Manager"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000002"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Siphesihle Khumalo",
                            Position = "Cutting Machine Operator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000003"),
                            Age = 35,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Lungelo Gamedze",
                            Position = "Maintenance Specialist"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000004"),
                            Age = 29,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Nomcebo Mamba",
                            Position = "Inventory Controller"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000005"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Mthobisi Vilakati",
                            Position = "Fabric Inspector"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000006"),
                            Age = 24,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Tengetile Shongwe",
                            Position = "Junior Designer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000007"),
                            Age = 38,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Bandile Fakudze",
                            Position = "Logistics Coordinator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0001-4a11-b001-000000000008"),
                            Age = 45,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Phiwayinkosi Ginindza",
                            Position = "Health & Safety Officer"
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Age = 39,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Thabo Maseko",
                            Position = "Production Manager"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000001"),
                            Age = 34,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Sikhumbuzo Nxumalo",
                            Position = "Senior Tailor"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000002"),
                            Age = 27,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Zodwa Magagula",
                            Position = "Seamstress Supervisor"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000003"),
                            Age = 44,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Mandla Tsabedze",
                            Position = "Warehouse Supervisor"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000004"),
                            Age = 31,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Nomathemba Nsibande",
                            Position = "Quality Inspector"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000005"),
                            Age = 25,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Musa Hlophe",
                            Position = "Packing Technician"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000006"),
                            Age = 36,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Simangele Kunene",
                            Position = "HR Officer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000007"),
                            Age = 48,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Vusi Matsebula",
                            Position = "Chief Mechanic"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000008"),
                            Age = 29,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Nonhlanhla Mavuso",
                            Position = "Accounts Clerk"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0002-4a11-b002-000000000009"),
                            Age = 40,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Lindiwe Bhembe",
                            Position = "Sourcing Specialist"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000001"),
                            Age = 33,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Melusi Simelane",
                            Position = "Lead Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000002"),
                            Age = 29,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Njabulo Myeni",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000003"),
                            Age = 26,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Temaswati Lukhele",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000004"),
                            Age = 37,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Sandile Dube",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000005"),
                            Age = 31,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Khanyisile Ndzinisa",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000006"),
                            Age = 27,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Mcebo Mamba",
                            Position = "QA Analyst"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000007"),
                            Age = 42,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Tfobile Dlamini",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000008"),
                            Age = 35,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Nkosinathi Shabangu",
                            Position = "Database Administrator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000009"),
                            Age = 24,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Sabelo Adams",
                            Position = "IT Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0003-4a11-b003-000000000010"),
                            Age = 38,
                            CompanyId = new Guid("a1f8b212-654a-4d92-9e81-34a6e87f1082"),
                            Name = "Gcinile Mkhatshwa",
                            Position = "Scrum Master"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000001"),
                            Age = 46,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Thulani Masuku",
                            Position = "Operations Director"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000002"),
                            Age = 34,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Zanele Nlangamandla",
                            Position = "Chemical Engineer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000003"),
                            Age = 39,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Nathi Ziyane",
                            Position = "Refinery Engineer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000004"),
                            Age = 28,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Siphokazi Sithole",
                            Position = "Lab Analyst"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000005"),
                            Age = 51,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Bongani Cele",
                            Position = "Safety Inspector"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000006"),
                            Age = 30,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Phetsile Thwala",
                            Position = "Supply Chain Planner"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000007"),
                            Age = 43,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Mzwandile Ndlangamandla",
                            Position = "Electrical Specialist"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000008"),
                            Age = 27,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Ndumiso Nxumalo",
                            Position = "Boiler Operator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000009"),
                            Age = 32,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Sebenele Dlamini",
                            Position = "Procurement Officer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0004-4a11-b004-000000000010"),
                            Age = 36,
                            CompanyId = new Guid("f2c90e44-8832-4e2b-b98a-7d1a23e59041"),
                            Name = "Ncamsile Dladla",
                            Position = "Environmental Officer"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000001"),
                            Age = 50,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Kenneth Mkhonta",
                            Position = "General Manager"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000002"),
                            Age = 37,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Mbongeni Vilane",
                            Position = "Forestry Supervisor"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000003"),
                            Age = 29,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Thandeka Mkhwanazi",
                            Position = "Mill Supervisor"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000004"),
                            Age = 41,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Siyabonga Ndlovu",
                            Position = "Logistics Manager"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000005"),
                            Age = 33,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Anotida Maphosa",
                            Position = "Timber Grader"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000006"),
                            Age = 26,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Lindokuhle Zwane",
                            Position = "Kiln Operator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000007"),
                            Age = 44,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Bonginkosi Mthembu",
                            Position = "Heavy Equipment Mechanic"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000008"),
                            Age = 31,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Nosipho Shabalala",
                            Position = "Sales Representative"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000009"),
                            Age = 38,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Sifiso Mdluli",
                            Position = "Safety Coordinator"
                        },
                        new
                        {
                            Id = new Guid("a0e1c2b3-0005-4a11-b005-000000000010"),
                            Age = 23,
                            CompanyId = new Guid("5b7e9231-11d4-42bc-a2d9-e932b1029c73"),
                            Name = "Lwazi Khumalo",
                            Position = "Junior Accountant"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
